; Inno Setup 繁體中文（台灣）訊息 —— 只翻安裝精靈會看到的部分，其他沒列的沿用 Default.isl 的英文
[LangOptions]
LanguageName=<7E41><9AD4><4E2D><6587>
LanguageID=$0404
LanguageCodePage=0
DialogFontName=Microsoft JhengHei UI
DialogFontSize=9
WelcomeFontName=Microsoft JhengHei UI
WelcomeFontSize=12

[Messages]
SetupAppTitle=安裝程式
SetupWindowTitle=安裝 - %1
UninstallAppTitle=解除安裝
UninstallAppFullTitle=解除安裝 %1
ConfirmTitle=確認
ExitSetupTitle=結束安裝
ExitSetupMessage=安裝尚未完成。如果現在結束，程式不會被安裝。%n%n你可以之後再執行安裝程式來完成安裝。%n%n要結束安裝嗎？
WindowsVersionNotSupported=這個程式不支援你電腦上的 Windows 版本。
AdminPrivilegesRequired=安裝這個程式需要以系統管理員身分登入。
SetupAppRunningError=安裝程式偵測到 %1 正在執行。%n%n請先關閉它，再按「確定」繼續；或按「取消」結束安裝。
UninstallAppRunningError=解除安裝程式偵測到 %1 正在執行。%n%n請先關閉它，再按「確定」繼續；或按「取消」結束。
PrivilegesRequiredOverrideTitle=選擇安裝模式
PrivilegesRequiredOverrideInstruction=選擇安裝模式
PrivilegesRequiredOverrideText1=%1 可以安裝給所有使用者（需要系統管理員權限），或只安裝給你自己。
PrivilegesRequiredOverrideText2=%1 可以只安裝給你自己，或安裝給所有使用者（需要系統管理員權限）。
PrivilegesRequiredOverrideAllUsers=安裝給所有使用者(&A)
PrivilegesRequiredOverrideAllUsersRecommended=安裝給所有使用者(&A)（建議）
PrivilegesRequiredOverrideCurrentUser=只安裝給我(&M)
PrivilegesRequiredOverrideCurrentUserRecommended=只安裝給我(&M)（建議）
UninstallDisplayNameMarkAllUsers=所有使用者
UninstallDisplayNameMarkCurrentUser=目前使用者
ConfirmUninstall=確定要完整移除 %1 嗎？
UninstallStatusLabel=正在從你的電腦移除 %1，請稍候。
UninstalledAll=%1 已從你的電腦移除。
UninstalledMost=%1 已解除安裝。%n%n有些項目無法移除，可以手動刪除。
UninstalledAndNeedsRestart=要完成 %1 的解除安裝，必須重新啟動電腦。%n%n要現在重新啟動嗎？
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安裝(&I)
ButtonOK=確定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonYesToAll=全部皆是(&A)
ButtonNo=否(&N)
ButtonNoToAll=全部皆否(&O)
ButtonFinish=完成(&F)
ButtonBrowse=瀏覽(&B)...
ButtonWizardBrowse=瀏覽(&R)...
ButtonNewFolder=新增資料夾(&M)
SelectLanguageTitle=選擇安裝語言
SelectLanguageLabel=選擇安裝過程中要使用的語言。
ClickNext=按「下一步」繼續，或按「取消」結束安裝。
BrowseDialogTitle=瀏覽資料夾
BrowseDialogLabel=在下方清單中選擇資料夾，然後按「確定」。
NewFolderName=新增資料夾
WelcomeLabel1=歡迎使用 [name] 安裝精靈
WelcomeLabel2=這會在你的電腦上安裝 [name/ver]。%n%n建議先關閉其他應用程式再繼續。
WizardSelectDir=選擇安裝位置
SelectDirDesc=要把 [name] 安裝在哪裡？
SelectDirLabel3=安裝程式會把 [name] 安裝到下面這個資料夾。
SelectDirBrowseLabel=按「下一步」繼續。如果想換一個資料夾，請按「瀏覽」。
DiskSpaceGBLabel=至少需要 [gb] GB 的可用空間。
DiskSpaceMBLabel=至少需要 [mb] MB 的可用空間。
CannotInstallToNetworkDrive=無法安裝到網路磁碟機。
CannotInstallToUNCPath=無法安裝到 UNC 路徑。
InvalidDrive=你選的磁碟機或網路共用不存在或無法存取，請選擇其他位置。
DiskSpaceWarningTitle=磁碟空間不足
DiskSpaceWarning=安裝至少需要 %1 KB 的可用空間，但所選的磁碟機只有 %2 KB。%n%n仍然要繼續嗎？
DirNameTooLong=資料夾名稱或路徑太長。
InvalidDirName=資料夾名稱無效。
BadDirName32=資料夾名稱不能包含下列字元：%n%n%1
DirExistsTitle=資料夾已存在
DirExists=資料夾：%n%n%1%n%n已經存在。仍然要安裝到這個資料夾嗎？
DirDoesntExistTitle=資料夾不存在
DirDoesntExist=資料夾：%n%n%1%n%n不存在。要建立這個資料夾嗎？
WizardSelectTasks=選擇附加工作
SelectTasksDesc=要執行哪些附加工作？
SelectTasksLabel2=選擇安裝 [name] 時要一併執行的工作，然後按「下一步」。
WizardSelectProgramGroup=選擇「開始」功能表資料夾
SelectStartMenuFolderDesc=要把程式捷徑放在哪裡？
SelectStartMenuFolderLabel3=安裝程式會在下面這個「開始」功能表資料夾建立捷徑。
SelectStartMenuFolderBrowseLabel=按「下一步」繼續。如果想換一個資料夾，請按「瀏覽」。
MustEnterGroupName=請輸入資料夾名稱。
GroupNameTooLong=資料夾名稱或路徑太長。
InvalidGroupName=資料夾名稱無效。
BadGroupName=資料夾名稱不能包含下列字元：%n%n%1
NoProgramGroupCheck2=不要建立「開始」功能表資料夾(&D)
WizardReady=準備安裝
ReadyLabel1=安裝程式已經準備好在你的電腦上安裝 [name]。
ReadyLabel2a=按「安裝」開始安裝；想檢查或修改設定請按「上一步」。
ReadyLabel2b=按「安裝」開始安裝。
ReadyMemoDir=安裝位置：
ReadyMemoGroup=「開始」功能表資料夾：
ReadyMemoTasks=附加工作：
WizardPreparing=正在準備安裝
PreparingDesc=安裝程式正在準備在你的電腦上安裝 [name]。
CannotContinue=安裝無法繼續，請按「取消」結束。
ApplicationsFound=下列應用程式正在使用需要更新的檔案。建議讓安裝程式自動關閉這些應用程式。
ApplicationsFound2=下列應用程式正在使用需要更新的檔案。建議讓安裝程式自動關閉這些應用程式；安裝完成後會嘗試重新開啟它們。
CloseApplications=自動關閉這些應用程式(&A)
DontCloseApplications=不要關閉這些應用程式(&D)
ErrorCloseApplications=安裝程式無法自動關閉所有應用程式。建議先手動關閉使用到這些檔案的應用程式，再繼續安裝。
WizardInstalling=正在安裝
InstallingLabel=正在把 [name] 安裝到你的電腦上，請稍候。
FinishedHeadingLabel=[name] 安裝完成
FinishedLabelNoIcons=[name] 已經安裝到你的電腦上。
FinishedLabel=[name] 已經安裝到你的電腦上，可以從剛建立的捷徑開啟。
ClickFinish=按「完成」結束安裝。
FinishedRestartLabel=要完成 [name] 的安裝，必須重新啟動電腦。要現在重新啟動嗎？
YesRadio=是，現在重新啟動(&Y)
NoRadio=否，我稍後再重新啟動(&N)
RunEntryExec=開啟 %1
RunEntryShellExec=檢視 %1
SetupAborted=安裝沒有完成。%n%n請排除問題後再執行一次安裝程式。
AbortRetryIgnoreSelectAction=選擇動作
AbortRetryIgnoreRetry=再試一次(&T)
AbortRetryIgnoreIgnore=忽略錯誤並繼續(&I)
AbortRetryIgnoreCancel=取消安裝
RetryCancelSelectAction=選擇動作
RetryCancelRetry=再試一次(&T)
RetryCancelCancel=取消
StatusClosingApplications=正在關閉應用程式...
StatusCreateDirs=正在建立資料夾...
StatusExtractFiles=正在解壓縮檔案...
StatusCreateIcons=正在建立捷徑...
StatusCreateRegistryEntries=正在寫入登錄...
StatusRegisterFiles=正在註冊檔案...
StatusSavingUninstall=正在儲存解除安裝資訊...
StatusRunProgram=正在完成安裝...
StatusRestartingApplications=正在重新開啟應用程式...
StatusRollback=正在復原變更...
WizardUninstalling=解除安裝狀態
StatusUninstalling=正在解除安裝 %1...
ShutdownBlockReasonInstallingApp=正在安裝 %1。
ShutdownBlockReasonUninstallingApp=正在解除安裝 %1。

[CustomMessages]
NameAndVersion=%1 版本 %2
AdditionalIcons=其他捷徑：
CreateDesktopIcon=建立桌面捷徑(&D)
UninstallProgram=解除安裝 %1
LaunchProgram=開啟 %1
